### ISSUE TITLE
Implement DefaultPageController for Area

### ISSUE THREAD

**Issue by dnasir** [valdisiljuconoks/MvcAreasForEPiServer#1]
Currently DefaultPageController is hit if no controllers are present within a defined Area, which requires developers to implement a controller for every pagetype in said Area. It would be useful to have a DefaultPageController for an Area to handle pagetypes that don't require a controller.

**Comment by valdisiljuconoks** [comment]
It's better to implement default page controller in project rather than in library.
One way would be to decorate page type with some info - that would tell which area page belongs to.
You can use `Group` property of `ContentType` for instance.

Then you would have default page controller in the root of the web project which should be "routing" to particular view depending on group.

```
namespace MyProject.Controllers
{
    [TemplateDescriptor(Inherited = true)]
    public class DefaultPageController : PageController<PageData>
    {
        public virtual ViewResult Index()
        {
            var page = PageContext.Page;
            var type = page.GetOriginalType();
            var groupName = GetGroupName(type);
            var viewPath = $"Views/{page.GetOriginalType().Name}/Index.cshtml";

            if(!string.IsNullOrEmpty(groupName))
                viewPath = $"Areas/{GetGroupName(type)}/{viewPath}";

            return View($"~/{viewPath}", page);
        }

        private static string GetGroupName(Type contenType)
        {
            var attr = contenType.GetCustomAttributes(true)
                                 .OfType<ContentTypeAttribute>()
                                 .FirstOrDefault();

            return attr != null ? attr.GroupName : string.Empty;
        }
    }
}
```
